sprite $TestLab [64x64/16z] {
lTO5TiD054DHcTb__wijg62QKHBhj2yCrqpGHU1kiSkWMvvcZcOMPuvc5cUEPXPd9W-7CzU7oGEQh_iYbV1BZMDDQX1PFkFQ8WOGfyg4hvxtCrBbvo1E3K3P
7ok0AH8bVGyqSQm2nfoF__6S_lMsRpzVkcA-wHjoe5ZYq9D-84zi1XkNFiErrrnxnP_ti-HC-HwTv2plH-1x06s6QxzM783coFXj088BlmsWKbnx3a1oxJa0
pRNd0CZxCUEXVQmjlyDTptfulleZ3_WUflVF7yRvopf_Xdl-thnr_U1Vlo1ahjUSEPovtkBCuSpIpE7CqSpYpE7Cq5k6tNg2lWC
}


FirebaseEntityColoring(TestLab)
!define TestLab(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, TestLab, TestLab)
!define TestLabParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, TestLab, TestLab)
