sprite $TestLab [64x64/16z] {
nTS5RWD150DGfqgoNzgfVF_JbdwvjSOxBZWCpyi4cU9h2YA6FTvnfiWvqEv8S994TqAk2ufcnhTyq8yOzw1WC2ee7imGOsydv6J8IUrfBHs3MmLdWmDwQ-Ig
v_U3tm6SFqRuwk9lF3z6U2BtbNW2zFnDxq1N_QaviEYRV_D3MLvn5eNtE2czvhw_5TpqEpR13T-lc-2E9xf0yBdl0i4DtmKdmHrFTBZgEUCryUmFBC4nysoU
RV-5p4FxYlm_xt_puqT-_4Aj-X4UlyFpXtDy_lAQa0CXnmZF7t7Kn-VFKK5s0J32wnSTamSDPqnInfGlDXJS37kwq-ltUm
}


FirebaseEntityColoring(TestLab)
!define TestLab(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, TestLab, TestLab)
!define TestLabParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, TestLab, TestLab)
