sprite $PerformanceMonitoring [64x64/16z] {
fPPNOiGW34JbBjQ0xd_Rn6FOAWUoyxws-9b1LFaRC_aMUu9G7t0sO6n0wO2n0QK3nWQK3aZT61smlf6wCJfWVMlgUG-gOS-j5_YoJbAODF_RtmHKDlEurEE0
VyPvNUTH3ePe3XT-W1ooWHpmYk3vrxhQ4ueNTFgnnetf-9fYxL3iyuTV_OYkCFQpuNpyskLljQKLvYYo8fKx2fz-llSzpUlvDhtN87_uptfzR7okHKs39Dhs
9wJMDPLlI9XMnR1CJJyZPHIPInZ4cOyG-AlbxtW-dKLBSh2Wb0aTs3y2VCmTj1nlPcYsbEyMpw_16YXQBa2lRIA5Vk5dns_aBoob-y3FxzUliZpfVVNBWb9x
96y2UlD7BqipTSvV3ypVtlK3egxpl6gqw_NZhrzK80nI609wtxL-w_uHHtbYZFx-OPVxbxpHkN-182wXV__krArnVbGQvmTnVb7df_7dT_N92mYZ0zPdTC3e
WFKf7J0we6p0w82n0QK3HWUKNI7S1ntg3m
}


FirebaseEntityColoring(PerformanceMonitoring)
!define PerformanceMonitoring(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, PerformanceMonitoring, PerformanceMonitoring)
!define PerformanceMonitoringParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, PerformanceMonitoring, PerformanceMonitoring)
