sprite $InAppMessaging [64x64/16z] {
lTP5beLG54FHu7up_zbMEhYJLV_qD_eCrv7u6XSPTCxGOvvM9bUULYPNdbOcLoQdnvNhQNBUyrZ6NTS-2gpB1swwuWFszTnqpfbXN_hS1_3y0RYl0v9wNGeq
t7RcMo3ZkWAe3pt_mNUcvr3bNtnKmR4ddbiF5Dqxl__lQUDvLGwMLtbdUPNKSUy9hXkwkioJyJNwdNzOtzP51Y1hFPzKyVxvimHglFiR7nWRV-9NdpLKNttH
E-Et3cF-v9qn_wpvkxvGuVZkX-idJE_l7yR-PUsVjFVlqNld1__y0hxCzrZdSULwaokFAqz3ULnvMfbSULnPUiomSm_e7m
}


FirebaseEntityColoring(InAppMessaging)
!define InAppMessaging(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, InAppMessaging, InAppMessaging)
!define InAppMessagingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, InAppMessaging, InAppMessaging)
