sprite $InAppMessaging [64x64/16z] {
nPT7TiKm30EHzzqj2VU_RLRfP0mQARCVg1SYPUCh6n84jvunCM4oRBKJl42rSqmz3zWeqX3Hg9FqtGXeh26DNPy3bZ5rqjJ9x_th1H9qAM0ATI5WApIVTs1A
_EaZ0Cwm0qnyVYJo2T_V79y0OwPx_i84qGTGyxTWHRlkR_6-UQX-lkzS7zW3N-1ymYkgdpzrhh-M_GDlMFFtiEP_MEidxvyjy8_2_dNFZtz-OnP8ldj__VFz
wxyV_lk5xQxVpFVR_3zCzl_b5LC7J1tD_3-2HUp_inNW5G3Dh5zoHDr8c731fewydh11fSdZTkltPm
}


FirebaseEntityColoring(InAppMessaging)
!define InAppMessaging(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, InAppMessaging, InAppMessaging)
!define InAppMessagingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, InAppMessaging, InAppMessaging)
