sprite $ABTesting [64x64/16z] {
pTL5WiCm0CLG1SlM_Myxgt8T-aFQlu2HwPIj-L10xmNwMgRLaAkPLaEkPbeDkHfoGwwfD-I6N5DloBNESz_nLEUdAdonD_LLRYcbl-A-bBBMgyFL3-h_zERU
V-kxg-yt-GDSErYjwYyyT75rBGzrhctagTtAxp_oqccLBmqlDMMDxtYhN-7tV6Y_UFxFVEoyTFyqVAnTw0SgZOlyWMh71RvGhodpvyyHwftcp-zJw6sfrhh0
bvvAG_d4mVG23JaXXv13waCE8OVKXnm8EMGQ8EIGQI3aGCWXqjS2Usy1_G8
}


FirebaseEntityColoring(ABTesting)
!define ABTesting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, ABTesting, ABTesting)
!define ABTestingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, ABTesting, ABTesting)
