sprite $ABTesting [64x64/16z] {
rPSv3iCm40EPmCS24Sp__pPTAYrCUQfClKDRjwIMyezIG-2kPsnks82T_eHlIEqUgFS1vP2X6SCvwR_d0SDhH6tF-y3BGDs6karzgDl9YWjMOpH1-g8jyliV
SEJtLMHy91NnBVc__M9-cVdEVR33NEppqYCT1RpZKpLRFr2N5dKKK9hmoITWVhgNObtpqbpNA_8ljSpyMhaXJNmHN-B-zjmlvJ_GLvOVCl3vZG8swEFx4mfW
rqyF2Vq0lZ-Z0FO06F3zqXFg867J3PMsV3sXb3BYTjFt-nS
}


FirebaseEntityColoring(ABTesting)
!define ABTesting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, ABTesting, ABTesting)
!define ABTestingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, ABTesting, ABTesting)
