sprite $Authentication [64x64/16z] {
pTG7SeCm58JXDseqINl_soOxvasQR0ERzazJ-rm1UnnWLmFU4kXRWlOapJJE9CqqpYJDDCv43eaprKFaa3XJFIJEDAvxI9pfVinHSqWpzkOKSZtbPsEXSTo2
iVc4htOhSHBjLZtki-qreFcuOD3O1pShiFWuZZq69JSRiFau7VUpcmvq7y_7FOAJjnSBEE5RTEul41k66SRLTUi-xjlQy4ypZEfrNTQt3_qwgVsmtqgmlJHt
q7CSodR4hplsSWFy8WphKv_jIqJ1N-t9_rziK0Dc7vV7zu-Dce3Dl8U-3tq6gddzFtdxxCEe0jJWTVNv_O-ytLAzYTmapYJEL2zn9d6cUeqpYJDDCuapIJED
CuapINk2VUi0VG4
}


FirebaseEntityColoring(Authentication)
!define Authentication(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Authentication, Authentication)
!define AuthenticationParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Authentication, Authentication)
