sprite $Authentication [64x64/16z] {
rPTLOiGm44DdEJ29xd_QCgWmgIsLzlqiFXbYZ981BmpH0xjAnX45HyDkhGI-GBCPKwy31ZIId-g9TgIwCrBfJDLsiG_GZQa3fWwuFkbMm14YWrSyGCNh5O11
xNF5ZkM_gf5xYWUucqz5mEQZvVSTVdpcX-0lG6xxWrV-iBrHi7yIHZQ7oIFp88toB3vS2xdG-xxwx-A5YRfpXnRMU0T_kIexsxer28TQPsSf0ePeyAEkGFov
FvX-EBwxVllxXxz_nG2HjFTlA-1e-kxvYJ7rIA7lhGhOvsShmBi0f7b_gV5qJf3la4D3oyM48Lh9vdQxz_TR
}


FirebaseEntityColoring(Authentication)
!define Authentication(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Authentication, Authentication)
!define AuthenticationParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Authentication, Authentication)
