sprite $AppIndexing [64x64/16z] {
pPS5SeL044I72Z9LBFJzJnjFyEbPElAxvEjxh8jTnl4Tjo24hNUqk4WhqDb2W8JJWW5G18vaoYbUaCz5sGL1WIHmLAQGqjE8E23YWCgBE92PSOdP6CadNe0s
RfkH5G37TBOEAS05tYoYaFShw_A-ZmIiKCtoAS_lFhOr_4VTbynH0SpPuu68TsWy7fBl57uwzX_dhu6n0b-8Plt1xgmhy_9MMfjl6Ver6mgSd5L87Tp04wwI
a0Hca0HcBWdg3Zri_IM2frE-HIudk2-b4ZPGnyqKUV-M1At8o-SdIQ0TFr745KO-Fqi2xG9GvFkB811lOAsHUBRczGQtR4gwtkhz_GK
}


FirebaseEntityColoring(AppIndexing)
!define AppIndexing(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, AppIndexing, AppIndexing)
!define AppIndexingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, AppIndexing, AppIndexing)
