sprite $AppIndexing [64x64/16z] {
fT9NSiOW40JX1cMfqDp_jgvr-YCghwUV-SXS9_7VT9T1yvEedwKZZqUMZZmUMJhoU6HoMJnolKmkYqUkbyMZFlVzCTT2dNPTrUL7vRkowQAENxbhKhyBFksj
7Gl0cFG7K9iKdHEmvdo5gjycuCpu0sYwLM1HhpT-Vhgo3QfwlT_-hhjE8ECBjESzjeH_6LvoliBnFE6fNgz-Uhhl7OeIxK_h3J0hKu7fyJCt9VQl3PZk-QoK
rmIKxPIq3q1Hqck4g01H6PDUAx_DAZ1qENhRkLI0ChVOJNy2GBrQEtzVa27le_u4D-zC4DwOWF361AGcc1slOPRbrU7WUaoEoS7au7gJWyd1zHwFJ0wUZamE
beuy7faS37tBiBV-G3y
}


FirebaseEntityColoring(AppIndexing)
!define AppIndexing(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, AppIndexing, AppIndexing)
!define AppIndexingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, AppIndexing, AppIndexing)
