sprite $Analytics [64x64/16z] {
xTU7RiCm40DG1l3s5Vp_h-tU5L7Ax6w8cV6q4jjta5duc0KYXkqVOw3846Xt4NmdhjO9kHvWePbgyg8ViVPWW69VhBtxPy3kX9mCEPdwFZwFQe31q6DhegNt
eXbRxmuUbmlWSK_aVaay0VvklsH-OUOPUDC5_X5bDzdFysU_P7v1vl49_W80RB-8QLqFiUgJuw4zN3ySzqlhpV7nguNRb7n-jMkNfw-URWz2FZzBdUeuypxJ
HFty3kk78VHn_HGDa9MVB21QG5m_HmDa3K25_OkEoOCH1hDrzNVkZx30JTdxJlltAm
}


FirebaseEntityColoring(Analytics)
!define Analytics(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Analytics, Analytics)
!define AnalyticsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Analytics, Analytics)
