sprite $Analytics [64x64/16z] {
vTK5TiD040JH5RFw_gSDrOj9jDeEfnwOvfkb2Vj98JNTPD1hbYP3ayF9qEHmCZGvd4mkWvFhPN8Pd5olKtpgsb4FdU1jUAbAzWE3hUwBvQgPpFLGh2y2hNdz
Oo_Vwm_xwSKLqvxNdfz1yuwF-TVNgJu7vQdlFmDbVzW7suTFyDFi-Fx5vMEo7q1pZ5_UTvbjOdrOtofbgiylHqrvUQOp-wDbTf1whlKx-slj2QhBQCCNSTcV
aGjuRBlf_LexxkzlV4fmCZYvtk1aS7AzmydWv6WoE1cQ74u69qTVSkob2FeC
}


FirebaseEntityColoring(Analytics)
!define Analytics(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Analytics, Analytics)
!define AnalyticsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Analytics, Analytics)
