sprite $Crashlytics [64x64/16z] {
nPTLSiHG30ILCjkgwFwd3NCoQTNEGd-_diSKahK-M4E0xYaPOmb6m-useW2o6T0P67Gcuo-o-a3R6QYTWRuZ2Qr7G6T0PsoVzHp7SQA0aGh0RYm9DL1NFyNm
uKC3P33x5K_eThVy5POMZL3TtjS1z_N4-9-_bWxO2r7xNXufp9stguPlUaGCngw4iwtdnutzjVpnY_3c3tf1wqSF0wnVEWVNrlvvfxj_5MdwK_q4pYyyHvhd
fzARvxSisBy_nEoPznVi3z3JlR-XVS1e-lRxoGg0dK5aXDK0-_ri1NWVWBJ_BqQ0-GCR0rYXvynAlqycs_rs_--F
}


FirebaseEntityColoring(Crashlytics)
!define Crashlytics(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, Crashlytics, Crashlytics)
!define CrashlyticsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, Crashlytics, Crashlytics)
