sprite $AppDistribution [64x64/16z] {
fPS7SiGW0CIukDl4_F-rwGq51ZHesXMBXNKFLVRqmnu4SFqOSwemQzjF8ZNmDj4w4QMNYKKzfdxqt8bE9usrsmwI1he7kcVKX-x16QVP4Qz1l6P7lARkxw46
_DrU9HxvPcLzgVjhmy_o2p-dBl_kzFTMkV6N-xzFdJvEC_g4_WR_RFkPmM-elwndnaK_EJze_wdcR_1htFCyJ_1j_P_YQkedvVetvRVhtxkFtbZoz_o7Cpm-
tRwpX-VVCpgt_gSKnHDEVlqwa0yAzMF4wUDh5F7uIJ9y_nYR09vTB77u_Zqqm3peZpy__JAeX-Yxpz7nHEj4woJgjHCTJgpkHvX3WrsiN8wmXrwYMFVO-_ih
}


FirebaseEntityColoring(AppDistribution)
!define AppDistribution(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, AppDistribution, AppDistribution)
!define AppDistributionParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, AppDistribution, AppDistribution)
