sprite $Invites [64x64/16z] {
fTLNOiCW40PXr6WcxFrFwpxf8UkVSNdxr5c5SMP1pJubKQ89JR8cdPEiIUSaQz8vgPnaJh8dbPFCIVRavotdPZzpyhw7QtjN_HRkRVOZ5w_XMRKVUNp2fz-z
_LF4Hyct5Ly4tuz0gxtky_tEBRV_fTal3NrTRxizMS_xaUtN1lpj_jZWpErRZha_BtlizfhdTiNREM_DoErJeAMQ8pm5IgRKu8i92Nxs-6Uldth_wA_dfm-U
7_7vbTUFrPYgu5c_s-r_wmFlcH_RmBlcrqcRdncVjVbTy4Np3TyqRt4m_lqRYFeBs7gjVS3n_k0aSvhrCYUPqwpNEScST4qo9rcJpadcDAL9iaGEUW4
}


FirebaseEntityColoring(Invites)
!define Invites(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Invites, Invites)
!define InvitesParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Invites, Invites)
