sprite $Invites [64x64/16z] {
jPTNjiKW2019ywMp_zs-a_ebmdLEvZSPx0fYCkhBA0QkMnEZLuCUsD5Eg0Ep3w1k1nWro9hLLutZzDq7jNuG6djy3lHda7w0z0Fin_MK2W7wM4FcQVHrwxze
yyKEa6aMxezXVyv-1BlCzoT7T_p7IoB9-6Dqx5cBvFHM_bIrE-oczbGijUUgaPST7Sg17chku_xp-Vjy_UZ-eVitT7vsSpASCOxU-UNtnuXsL62HqkEdkljt
BEG8-FtWxrTu1kqSHbts_OEptaCVvqye04i_Zxb77S3vCmh02e0LroyW0Ap0Ud4OtP478v0IU0sFczRl_m
}


FirebaseEntityColoring(Invites)
!define Invites(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Invites, Invites)
!define InvitesParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Invites, Invites)
