sprite $Functions [64x64/16z] {
tTQ5WSCm00J12tEs_sgVIHJQvml3s1OhfmEvDNo8eEzn6W2d0Sa1fm790QS1oG79aHoiHt8a1-iPykFY29p_SiIdcHuPVjdwvfzf_jlzaY5FLXHP9SC3zFW2
oYow1pZ9nmSO-uOt1pZfZmrl3d0yw-SCCcyyFRyQ-LNFyp_zVa_pql4C_3oPDoyzJzVlasHVlbZ_DTV_DVNNvejyj8_oTlpA-GCvV_dvqy_VVlqGwvTQFx7h
T-7D1aJon7h94ycJx_NfHF94w9T8dZYTHF8aaYT6Zm-I6y9vUWy
}


FirebaseEntityColoring(Functions)
!define Functions(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Functions, Functions)
!define FunctionsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Functions, Functions)
