sprite $Functions [64x64/16z] {
tPS5ZiDG34GT9ajp_zCkyzggqrUUiAKt-GoMQjQNPajKOFTxz4hK0xgQ21qGe3y4yTnWLb4UugwwahG30nSocBLJdgI-B8XB49Sed-EXeMK6VH2N2i4v_ltE
O1-cgj4lDVQcA04PNZ7u5qhmpC3CvWIl6GI62IurHRvHegR63qeq1FpC-5cCroto7yz_ZqVaxxt-PiRF1dZSV_duGSSlE7xIyPlF7tp-ildO-TFX_0tN3pta
yVe96R3bfzmC9G2ldv41sm0uthy00xW3wujRrthEwmwpLUNbVDFz-pC
}


FirebaseEntityColoring(Functions)
!define Functions(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Functions, Functions)
!define FunctionsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Functions, Functions)
