sprite $Extensions [64x64/16z] {
fPTNpeGX30FzzOfy_zF-lUuIZ9LvHMCw2WZP-SEE2Etw6JC3Pjls1q61iZL2ruX5rzoeSRCVCNQDw5qZvkwk0Ms4hX6w9kzh_SR8aF363HS_kG0CwZRMSkSV
7OqHrBl7EykVFHwR0mXcjVxemCI0YczTxEUJkre-dvgAq9NFIUZAvsZen4uLm1Px_zNSSV8PwM_yP05m-3fG_kphQUe_0Hi-kNmTkBd-2HEw8gblENzYQlmZ
9QQ-6m53HGUVC7G2_LEWzFqt3DXJzK6Oswt7BLfdes3iqNUHBNIsQnTvQ6yHpw5T3oVhXpdff-kdL80eFzqQcYRf-ZaLaFi0tCd_Iuoh-map1BinSpDXHo-t
CU_S__qL
}


FirebaseEntityColoring(Extensions)
!define Extensions(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Extensions, Extensions)
!define ExtensionsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Extensions, Extensions)
