sprite $RealtimeDatabase [64x64/16z] {
rPS53iD030HT3bYQ__-smefyYjCfhZ0mUtosOwY9XwOerMBtUvmPw2peRYVOq3Oj7C0OJ3IL9PxqLVVT62JAO6AdqlGUGE8WSR2ynA5puXgdiNtCpsK7pWNU
D9YgvlUSxy4xIjN_JeOdWl_c9ypyC-5uti83_yhxyH_6-07N0NvFTl-6u-CjFD3c9yc7uUtzxUE7ZrynyQHInszbS9Qypf-KWKi_INarwVnP6RW287Nz8Wn4
1TQg8QV6o5iEfWJEzhXj_Nu7
}


FirebaseEntityColoring(RealtimeDatabase)
!define RealtimeDatabase(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, RealtimeDatabase, RealtimeDatabase)
!define RealtimeDatabaseParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, RealtimeDatabase, RealtimeDatabase)
