sprite $RealtimeDatabase [64x64/16z] {
pTK5RWGn44JHzZAwxd_Rg0J1yggL7zWl77Z3OzVZfFfkqbk0liMq7DAESOUqOzmXxHXta0jnHxqW5-AEUY7k8kV-D2esJlfKvhNiom6I7si_aW_hRZDqgwgc
dmhD9_JA_d8BNR9NyBa_z9k1_4tQzBoYdzAMp0zNQVGz-FxJzH_N_jZnEgpuGGtlPang-Sk3Vk7xgr_mOxT1_YvjsfvylujrvtaVBPzMRchP9da-Vy3vgqGd
KCWBSOUuenvnXxYZdd67k6FQ8UwGTemxn1tGRm7xLeE-
}


FirebaseEntityColoring(RealtimeDatabase)
!define RealtimeDatabase(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, RealtimeDatabase, RealtimeDatabase)
!define RealtimeDatabaseParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, RealtimeDatabase, RealtimeDatabase)
