sprite $MLKit [64x64/16z] {
fTS7RiKW48JXSL_bhRJtFsqAZZmfm8hXLqtv69CUDBDuCen5gvonHwDTrCoG5KcgPY9doGSzpy6Ofuw9pyx4TQRTdRdsz4paJEHirfEByJjEopYlrP_tr5jl
dczQWQFz06sEzBq0MEhFxahK0n7c_Abu4A7hBVDdrxSuqSoF9yvZc5ytWkhV0Dpp6ptBkD--KCL7yMMUVc2--5igFeg_0Apq8_F55wZuUFoQUAln5ttqlQ4w
__WryK1jdZuK7uzVSs__v-dvIlRt_UlpnQ-PHyM_VXsT-_tt0LTyvtpFhS5jzlTNoLJkqx-_fmxO9psOo9d6cMiVUoRECv4paJCNxyx4SQPobkaTIPRUN3x1
4iXyyDxw_-yV
}


FirebaseEntityColoring(MLKit)
!define MLKit(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, MLKit, MLKit)
!define MLKitParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, MLKit, MLKit)
