sprite $MLKit [64x64/16z] {
fTG7ZiD034DHfan9R4ltF-qMOgFKqMBCZvBwJ5GXpnrxyuS4Ua_JJD5CuapHJE9CqKpYJEIkSAPw5xahdAdU5SuqhdjF-NOr_sjPiWSCE71mPmteO--VAm1M
lZC0frc_8dpRuqjummw_8NnBl8zy2M_8V3fFt_Ru4jumwpaVlatwc3_I6tBl6CmVEdq3K0-97yrVw3blavxpJizvppm6y_GBvsTypDEVEJ_fEK_FRCR7VFZg
gGS-pVUxj_yyFis7hpxZOpwypVYO3rzzniTyUBlvUoMzFvmFNvqTyTYQtUz3dEebvhtWCSlyMkFIN-fjoLgzjthY9mEOwY5oA9mfdAbUuKpXJFKIPmfdacOA
Pufc4cSAPugE51lbb7q3
}


FirebaseEntityColoring(MLKit)
!define MLKit(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, MLKit, MLKit)
!define MLKitParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, MLKit, MLKit)
