sprite $CrashReporting [64x64/16z] {
vPT7iiCm34EnIA4dck3-j_shk4EcYT_pDYcO1qbCDIJ1aO2cxrOwBXHS33kx2HwGjJMchWk2IHhsQCmZzcuKD9v3dRqu0vx6r4bJ9sr_qgs22uj4TtaixkeD
N6Gskwis8ADXYW1Wq1kWB9WOAFsW8BG-0UXeHi77WjC-a2hOE_u3WWSt13sVhjyz_kR-R_Fzyx_x_CFp0zxvyUD-M9z_dUHq7JqnuzdnB_NVr-Yc959vi4Yp
Vx-jWelfOyBK0LD7AypUse3z_zagy2u0cddzeadgHiC51qJYvCM6G9QMFhTx_Vu1
}


FirebaseEntityColoring(CrashReporting)
!define CrashReporting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, CrashReporting, CrashReporting)
!define CrashReportingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, CrashReporting, CrashReporting)
