sprite $CrashReporting [64x64/16z] {
pTLbcWCX48JXfeSOLlS_xGeL3vCdRArz_zyHr9u7s5V3LGAz96acQAPm9cYcS2Pefd0cSWYSgHuYXy2PwY5mzeJhliQ6OorM37l6WtaxShTGCMpTxytCsv6R
xTSziFw0w1x9fpssTcw7UL_2nOSoxQlTL35kv5lvo6-zbu_Qo0z7Rjp-T_p1FH1upth1_V22PuK4FJwiODZOfqUVC4xrslZ1_fz7QmV-V-ln_m-j_S3uszZd
HvzVtZyfniLwiMUz9SOqzCBu_OolwIE_fPu-gXFdJxdrPVRyHYPa6TCUTR5ZIyMaPsMxXB1i2rOvWtg1Yjm4pWJEL2zm9d2cUeKpWJD5Cu4pGJE5Cu4pJHyJ
xAKNw3i
}


FirebaseEntityColoring(CrashReporting)
!define CrashReporting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, CrashReporting, CrashReporting)
!define CrashReportingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, CrashReporting, CrashReporting)
