sprite $Hosting [64x64/16z] {
lTPNakCm38JX5fH01VRzJxixUUGkg2YCm_zgVyeCa2GIVus7iZGifUFIMijpBQsrFDVIMijpxKxEDDVkzRoJKtY-UpsRlAx5lQorTO0Ok-4hyvhrTSPDSsNG
ATywIDt6e1DVS9CP09JOjpacblW0iTyWhUHk0BPBldR2dIIh0LszukVZbM_Rnizs03CrzMJ58PUd4bm09J_pDC3Rtd2eo6knqCUNRsO3zQVQyYlGzG3Gave1
AoNr1HZOntu42XivC95zw2V0htdsCdJ4DwvV3Z3oio6u_k3v6UK0O-FvnI-f5n--FqRVJv4lQKnyF_IVVutY3V1huwTyFUwlkc7mi_4JZz-T91SS6kFnUp9_
MFsyW4DTD7_mRFwodIJt4SUspFpfEXUXvEPlyyfPkDPOFymowqT-_Rfp_UIzwxVuP0_Sl-3r_jxze_PQZw0qr_9QItCjhRKyrz9SI-gumEQxGFy3
}


FirebaseEntityColoring(Hosting)
!define Hosting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Hosting, Hosting)
!define HostingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Hosting, Hosting)
