sprite $Messaging [64x64/16z] {
fTPdaeOW48JX9d-IvlwttIcB3HQBgT-_-fW5S9u8tYP_8kXlZ1vnMYEvnccDv1gdDP9h91UEQwmNaWl7DTOBnxLJpliSB63zfykgCxuPO1IxB5hx0CtwuA2P
kl1BhWonYMZP0YZFV3YSCmAcF_5PGPFV8k1l-neDW2n_iq2L_vfz13GxNL1S-Fd1mOHKflrCRgV-zy7bnVk0grU-h9wqnzvsuTtgJUTFyj2cQplu3ZXPrYnW
vAmA95dNvZkONjD7ZhbyVBVXxFhBV7x0f2wZvk4kxjzENWj5HYsVUR50cRrcDvcR_GQODlkzUEVxiu0vdCeP_EJpvV_J3G3ZurwIlPfJSDWpdtxkfJlyP0uR
oXOjWD3ElBRPsIjEtevxEFTQhrdJniNRvJDyjE1os_zRx_bGHLvxEvxxE-_B-SMTUfCwCm5dMKVE__YDunhhEQvnN6CzoJMEQuGUSLpZj4PoZUCQfqU4_Uq6
_G8
}


FirebaseEntityColoring(Messaging)
!define Messaging(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Messaging, Messaging)
!define MessagingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Messaging, Messaging)
