sprite $Messaging [64x64/16z] {
fPTNbWCX30JRwyame_kVTdEseFHG_VAgoKbDDljcam-x8ncJDPWIThGH1f3DWCx0e3DL7jNYGDiPg9s1lYCLMe-0pe3EP7tGcSYE2-n6oD-X0OtgJtrpwpQW
7Sq3t2pxtR1EWAIDS--zW5QkcH_0ljDZnVsRVlaOeCqTzwa4_Iqu8R3Ik9qV78EwBSkYDzY7_KR-0l4d-0y3RxzO984_FrRvgqdi2oRkQS2Fto_b8K3V-3Ll
C4LmZ6oAN2khljXn_xNhkoQz0RvLrpydDpDmyoxwuOuJrklEvPPcBaculcZZRtg3_NxuDhgZQ_h-JWLCIJ_zVae5mFEJg5Ag0UdtSoeWzm6ewVzB8Y3v0vi4
RDZpuOHDKMgutzd_-mi
}


FirebaseEntityColoring(Messaging)
!define Messaging(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Messaging, Messaging)
!define MessagingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Messaging, Messaging)
