sprite $RemoteConfig [64x64/16z] {
fTLLSiH060DX9LaqwVwd3QbInadzw-vdVwOX_P-jitaHe7D89w0JuGdeH7W2EX6U83VWYNf3Ri0JzGOybJdtGz--WIjUZHkKlVg6Tz6hVysFtQAxSeEwlsfV
N_SF7NJrjgQ_IE-NkGzzT_6k5lStw3mtX1D_CV8N8n--h-Wdrvjz8URv-zF_1yVFSFxm-IjlkloMrVfihf-sbzARxVk9zVl7-xtlAxxxBPSEXVsBxPzy_-Rd
1po_P7g0GYx04-29Ui0Ju8bwmXFWYUW4U08w4Pu0Jq3F0JjNe5y
}


FirebaseEntityColoring(RemoteConfig)
!define RemoteConfig(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, RemoteConfig, RemoteConfig)
!define RemoteConfigParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, RemoteConfig, RemoteConfig)
