sprite $RemoteConfig [64x64/16z] {
vPSt5W915CDS43RCUxx_RUcerk2FIjGHvCb9aSrlDWKATvvnS-06xBOI_a9hPw2U0pQNh4jzkIVK7GGipwZQtlU1nq3TXhfDVQZROSNLRAnuUr2yOWLSSVs_
YQ_hRxVIJm6JNIBu_KxP-vrkRTblsh-vznqeVJFVpFUV-wA-e1y2wFpLnstvrgpVtjV4TrC-tR_W_adtRtv-yFDBctzauVCR1ToWZ-zFA81TFxqaL05yVqO1
x06muFibK-eWuLO-NVkMzmcRMbRTRlf-Vm4
}


FirebaseEntityColoring(RemoteConfig)
!define RemoteConfig(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, RemoteConfig, RemoteConfig)
!define RemoteConfigParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, RemoteConfig, RemoteConfig)
