sprite $Storage [64x64/16z] {
tTK5beDG50JH5znx_wiTwpXsFZLUyS359RQJucYw2z1RI3kW7U4EQ4Uu0zeHxY0Nu8vwGIx07VK2t37ElHRvq3QNjDVSgufRkNQQypxkovDz4m_btNtJlgzZ
gmRw6FHOgczcNac-_cTUrElhVT4UM_xiUWxKHtmsVNm_JPBA0twK2dz8ofDz9qbPzFfeoXBtlqSSEycDfnKVYxxGSqEAF_N3h2h1hyLzqlLpNfzo_PvNwR6j
-yUyTj2MJoySzG5v0Eu0TzG3xW1tr1Fk07T4Ey0Tq8vm1xW3-XQmjxHFNm4
}


FirebaseEntityColoring(Storage)
!define Storage(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Storage, Storage)
!define StorageParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Storage, Storage)
