sprite $Storage [64x64/16z] {
tPT5SiLG30ILAeCMgj_tFssO3ChtUCAzxtaCYfRabGo5fQjd33GCigrtWYi8TeEfzm79GMfNBuxJzDq8AAo0HAIMFZAc3gOEd-Q35J1malIQX_tcwvL37M39
ZNeRi4JQLzkTEuKOm98nFc8q_N3zSUsdvWyiIJoV_-OFN-2NvyDmocT-rk6ClpYUkh_QtfsVZJ_no8KNzlsCnZzusKNZi-KY-2rRFqq_d0zMc7xpVdIm8jtt
wv7a96M_trR0OFhs_yaAyBwVL2n1nFu_Mm5U0L1c_TAZwdh245T8OUHYGiPHIXYtLx_V0G
}


FirebaseEntityColoring(Storage)
!define Storage(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Storage, Storage)
!define StorageParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Storage, Storage)
