sprite $DynamicLinks [64x64/16z] {
fTK7RiGm44DHRcyQyFwtpI1XkaK8vaVP-jmbmKTYR_nHG3kLQ9NfBk0gqrt0LQQxWAkGC-DTwXboPhnBFJFUhV7SroXkjiBh0dINuaRofWUW7XDl-HtTyNn4
zp3Uy5EHh3E0cdZBBtf_qblZ7MTj_jNv4bV7xHFWlDS77tpl30ok-wBa1SyT-xzBDGU6EVyPRqNnYmx_ml_1NdbnlIdIv_bZbJys-PrSE_wot7lz-_oB3_55
hoirnBkd-98lu2ZrzVZLbF_tGuV_w_6RUqptJtFVZQS4pPMtlit9S-yBmBb8rcc1OpBdQj8KDnv-qbxrVj7mtYzQddVS6rJ8aV4kurtgCzvbl4jzm5N6kq2h
Z7UPxWAkCjvbMXcxtW9z0m
}


FirebaseEntityColoring(DynamicLinks)
!define DynamicLinks(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, DynamicLinks, DynamicLinks)
!define DynamicLinksParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, DynamicLinks, DynamicLinks)
