sprite $DynamicLinks [64x64/16z] {
hPStTWHH3CDGE6WZxtzRDyxsKjBZe0SL9duUKlgaS7Xtd_6a1pm5zhG9DNHsZzMJWDAGA_znrPoczvwcUe-TVRy3hGbrATIbr0zroJznFPMLbqRbpP3Lbx_m
mUL1TZUY2m2grLqb6EWc08QwjFS_TUEN3A36BxN00zzIVEgmz-kR1Pyv6vsZzOk6NFxLIrEErhNIzSyZGsdl2zHInXyzeOqFDe361wYzpr0Nb0beTG7cdJlH
wL_Qtdzo7mrFvTylFwBd6d-_eu2dq8TFGXr2dMlu_uYMnF_FKK1s0BZ6vvSa08iQdcYewUJxX6BATJntUdv_0m
}


FirebaseEntityColoring(DynamicLinks)
!define DynamicLinks(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, DynamicLinks, DynamicLinks)
!define DynamicLinksParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, DynamicLinks, DynamicLinks)
