sprite $Analytics [64x64/16z] {
tPVR3eCW44HNlE45v___jZOeQLh0bR4-k4_4p1cHgBiZaYr0IWiVHQ3dJP0kZjOOuAWuEcy0NN5qoW1dYiH1uhy6u0p0yG1d0Cv08NQ3dLC62jo-TMqnFtcX
ZHeeRjzvfOa-WOAl4plLdlrJUV0y7ioxbQjTZaUENpoqv7Z5Mz-LyYPyDMNxhpnKFPWNcfS_y6vX-77bp5pC-tzrjMZusBLDssjvYNULffGtuQjfWjEP_c6z
TbeFqg_6W_xrRT06QRyTHA9_fXheR0Uth_QkdUlVPUC3BfnVv7x-ulbHxkN90PmB06G0uG8GcR_80CZbJoO24n4y9ta1
}


FirebaseEntityColoring(Analytics)
!define Analytics(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Analytics, Analytics)
!define AnalyticsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Analytics, Analytics)

sprite $DynamicLinks [64x64/16z] {
lPVHieCW34GPbHdj9RF__xU5blRQciJejiqJEfm5Gqn8Igu1wQnXPGHwN0IsSNH407l6qRu0OiRHbW2E68c3nBS2u0J0yG0d04u0e0JmPLwAU08xSBvDoc8A
kFZoTD9Yy2u-jnd3D1W2Utp3nxPpcUf8Zl8Dptqy_W-Z_1g7g5CzNjBBaeF-0Sxs_-vukJzL3vG3l3p8d2udrfyxXHO-nVb-stNbWUU-_Qn5aE_vl1v8zCVI
yIMABoe-wx-WS-u1NEFhxEa5BpOEFIQbKztZ5nDN-BhzeLFFy1CxXMrUbRxzj_0pCvYvFWBdhWNbcd0yR_AL6OEuohVpdsv9QmpWoSYvFMdE-nNaQD8Ev7-t
QCJgXrcqjWNmRFt4X-ft8d7-_f9-pt_u_fX-ovCNSAu181iGhW4Y-o-o0UJwJwO59bfmRyeL
}


FirebaseEntityColoring(DynamicLinks)
!define DynamicLinks(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, DynamicLinks, DynamicLinks)
!define DynamicLinksParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, DynamicLinks, DynamicLinks)

sprite $Firestore [64x64/16z] {
lPVh3eCW38M9Xc2CiU__jilctAYqvU1Prh_mdT0Rq9H24qbtJIeZq74HyOsZ4G7f6KV70e8PHti2Cc8aBYJU2WWd81mlmWa89-3lMLT0mDsmJ2bDoqr-B-Tw
sKC1SsdBTNpo5WXORi_N-fXNZxVTRiqAXCKN1IcfWl2NGojNXlWpQ5KeBGSSlaxQ9vK6RyQaZTKHKuolShKiAgS8_wsLuzXVHxQCy6q5UjNt4l0QR-vNduID
rwy-wJMUDhCDZVYfWoitCi9VsbOryX1_dhVo1-TrlCvuelNRvkl89zO_Thqy0u7mJPgs_7PcBmXl5w9p1tVvARo3HpvStlsP8Dw_ln5-zFtGEphlLoWGDYxm
_2FlzxtlW_pm_vB-p__u_vZ-ovCVS6u080SGRW0Yvozo0EJcJsO49aRmQCi3
}


FirebaseEntityColoring(Firestore)
!define Firestore(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Firestore, Firestore)
!define FirestoreParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Firestore, Firestore)

sprite $Predictions [64x64/16z] {
lPVHaeKW28RHpD8qtlzjLzkpCvfe63k7YveXlry5R0HWQ8Zmrh0m0JelWdsJqHm1V38PFHP0didedW3Ec1178TuAe4m0PJoYJ01b0lSleNfT5gjNBT0e7qj2
mt8KBcjFHAUHnQE1TGLJUaw0JOEZTa1iBMP_jLRSaaUJ8Q1Yevl18OtSA9x2VVxWRrjATZ9vfRtNgWefcB21vV5kpy-zZ9RDoJXjvCrVJcpSk8R6kAV2LlAF
k5Eml-KJ7Z0E1CRyXMCMS6_u3vxoKTTo9J0EdVkKtZ5_lAyQp0BXNeeJU18Ou_20jmU1nNFn3j_Ylmay0eidPj-LnsWMLlx9nMlGV-NmS7xelMVloZb_dT1n
-LxacUlluNJyclzFD-zq_aONJKxDDxoQmbi-pEEa0E_0GazW3gzJ4DGiBh-_mFVvVxu_mdTvuGLSrW086n1P0oJiluGDeAp_bBJ0WXPyDEG7
}


FirebaseEntityColoring(Predictions)
!define Predictions(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Predictions, Predictions)
!define PredictionsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Predictions, Predictions)

sprite $MLKit [64x64/16z] {
nTVjRi8m38LX5zQcq99p_tTButnq4ukfUoQMNv7OunTfA6r4p0N8sOLlYw3-8UWlJXyPW7UBq_O075kSxWs0Pv4S97yT06u0E0zm0y0D0AW1-2SFap_kiMwN
nHhGuI93sGQHkUyxeyVjerLtSTjTlNwLviCPFpQVycx_aEQ3uT7pO_EQDxoHLn_E-B7vd7Vwaay-dF4fVr5VybqFwUI7MNtAJuFXU_cRUir7fzSyr6iUW-_x
QrxzedcdptdrNvft-fnNd_C-N_BLRtdBl_x_KtxUVNpdvVTyyIdlyZLVV7JwbizUynxVyjd7wlSrckTFowlFULn-F2jNw_mUsb6zj7mz3VOVHD-lKplfRrCj
nJ3jQptu_70y05dFFh-5vFpxYtpU__7xetpMao_Wt0M0l81m5o3o_aLU0Bdx9tC59gxWrfyy0G00
}


FirebaseEntityColoring(MLKit)
!define MLKit(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, MLKit, MLKit)
!define MLKitParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, MLKit, MLKit)

sprite $AppIndexing [64x64/16z] {
lPVRbeCW34K325fScF__su9EM-KccJFJF2cw3u5084HTOwRV6fyCGEKYt3QC7X7WEyFelW2F6KQt15XY8CuWNWem9i0Opum9C2R030dmF_2hqugqzGC2DLg_
jDNZLg1iNivpQs_u1cvz2EkSdYOXlyP67OxdpSQNHSR7iUlFMnBO97pgFfpU5T7SSo1lSjcKFIxk57pD_KlKjzuAgtnIL_Tt7uE0BtvNCZxwl-Q2Mti0HOlD
vjl7HIpPLJxhpn0vqRPKbm0klUch-Py2_X58UA_xMcZjlc_J6BoXcz5NbyRqi_TVEM0IykS4uD9y647yZqKxxnb8kN1uOyRtpzj2sDuHR0cCPT-sm63sRWgC
Pl-6mFZfKHSWaO13U3QE8Rvz0A8yUduJYEFt5_e-_yVtH_ek3rx0iG80B42m0WYily024Ai_aH8OAC5xlpm1
}


FirebaseEntityColoring(AppIndexing)
!define AppIndexing(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, AppIndexing, AppIndexing)
!define AppIndexingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, AppIndexing, AppIndexing)

sprite $RealtimeDatabase [64x64/16z] {
pPV13eCm34ERRWB6Ilt_VpkE4pXTYW7DnwZFGb5ewfIQ0j9HuKi2scy2NneTCS0lQNJR035fj6U07eauH7nl0Cq06Wze1j0C0Ca0v_AJyVcqYHjiSV__u0QR
clcyCPxKIYKg_2ohLTQj-eSyE3yNefdpNHVaNNmsYIz03jwHb5_x_r3smzkRuWZVC__i-qUV7oCy1WyV4EBNKQNYtTfLveOkcBzq0M_FBF5BU7xT-oCslqxj
LHSByzjYzjkN8xowFxhtr-7zYPFsTn9n_VsIxkTFVZ-cUtdn0Qu50360Q058p5zY0DJofnA1XGZUEl81
}


FirebaseEntityColoring(RealtimeDatabase)
!define RealtimeDatabase(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, RealtimeDatabase, RealtimeDatabase)
!define RealtimeDatabaseParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, RealtimeDatabase, RealtimeDatabase)

sprite $CrashReporting [64x64/16z] {
pPVhheCW48INIpnUW7d_josAJUiHg3ZMTE8F1Rz9ThckI5M0d1NUHA3j9YYBeuyOu9Cukcw0O-BeaW5QHE8WyRq1E0DmFC0PW3C0A0DyW_SsF5-3zJM3FAv4
hmP1YwePP7lws94C8YxIb_b2S8k1rV4fupKUtMjy_j3EE_NYbMlc_NP--xB1hYsuABtbzTmMSdm-Srdrz_23rclkzA8rXreFn_Wv-Gb97yciC0HvVjppOylA
elYM_45-ZqS8Gue_B4hn3o5y8V-5yP_s_7Hu_OpMcXImNPJUZRNZCRvj_b_F-p7g__gVstp3_kEsl6lTlzSXM3MXcOStJzfudE1Z39rHodJkqm5uzlp4HUUt
a3X_Vv7x-OllZt8lJrx0kGA0B42u0eYilyW2aAi_cHAOAC5hlpm0
}


FirebaseEntityColoring(CrashReporting)
!define CrashReporting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, CrashReporting, CrashReporting)
!define CrashReportingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, CrashReporting, CrashReporting)

sprite $Storage [64x64/16z] {
tPVR3eCW44GHh3VG-V-_RQsnWQB2CbQJpekwuOn4S9TLwb20AXKy4QZS1FlYw1m3fCJHnmR84qVl6K0Y4WU9nmRW3C3n06S0pW2W370JZqtSzTsgF8Cmr7YV
rUJmOSG6wsh4V1VkApFucj9yUvXVEf9NBZOGyV448EBRF-F1ylWzN_TbyzUVVw0juVNqlg_cJVyeu4UWNYul6J4_p4zQsIKyQU7wBmF7OOsFrGw__V_KqS8u
2LzP5wcHl3z__rDyAdz6igBy7Qb9vt-_VdofTndrew00ugO2IjR_4yylwdh-vFEZkfOd3-1S0q0s85m3HFPVP0F8zPzC2qoqu4T3dW00
}


FirebaseEntityColoring(Storage)
!define Storage(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Storage, Storage)
!define StorageParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Storage, Storage)

sprite $RemoteConfig [64x64/16z] {
lPV14eCW34JJDewjsEx__wrsc4uTJJ2oofuyy5P44bYHeW2f5HOYqECcyCNH4GFiYQFB1eY9epq37169WyIt1k0CmF40Pm3E0A0CS3q_9jyWygfHV8CORng4
ltxcBOCI_nuMwiKqAF2TKQ8fpZ-j4k-i2TYyYjprhySNLsi1dEdFmB1QFmN5AoXUGV7grK2C_nojhHMFgtXs_etMp_j_QBP_lFsxCSW5awlrjLy_udNLs_pS
LzJl3qzRFaNutB3oqB6-VuNx9zk_svmVXVEh-lp4IUUta3X_Vv7s_CdtHsdBanTmBW2G0OGBG6J-8WCWbp-P24n4yDAG2G00
}


FirebaseEntityColoring(RemoteConfig)
!define RemoteConfig(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, RemoteConfig, RemoteConfig)
!define RemoteConfigParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, RemoteConfig, RemoteConfig)

sprite $TestLab [64x64/16z] {
lPVf4eCW38IZj5vLylvlMulQiHm9iDRzuqpmMpaoaX29OgPQyKa0Mcx2QM5qZW5hmcZPWFE4qIa3BX68CuY71emPCCQ7m_OirS0RMXxUwfvMDF06viZfBeA1
7syZlCddvsXwfLVWHqUYTlXLG_HAxg4V7DRzyaA6Q4hnV0_lvc-h-Uxpw9kvadU1dgXP0eCSVjpn80rYgH_XKtW17yNp-JYkyBE6hmO2Fr2luJ4T_BH2cq5N
WdzvQtO32PVclnk8NnVtpnaOSVBo-Ja3SUtA-LkZu5h-h0OE7wRKJrp9FzjjiLh-246y-HD_nV-JhkRH-wFq_gg-F_cY-pkOG6dz0DSl5VKJNrb_uVKZtSk3
1JZM080D2DO0WVqNs01Y_IVI0WCjkFJA6m00
}


FirebaseEntityColoring(TestLab)
!define TestLab(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, TestLab, TestLab)
!define TestLabParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, TestLab, TestLab)

sprite $Authentication [64x64/16z] {
pPVhai8W38KP2YnoE-__jhPCKNQ55lPqrFnAgjzfAE4I8GuD4FyrL4QWyoBe6qUF2E3CEFfO06F6qJq1p1Y9WyHV1S09WEC1JW2S0409u4CyI7mN8Fdc3q5B
PKjWbTHXYhSvCHatFyeSs0a-x1zMRS6o1s6SrsLcrWHYyKqdWSPJMHW7t8g_jFdMKrKO3tXH3sQCjuL9G2g-7UVB06mb9Z71nwLwOnPOOgU2EfKLd4_5Jzv5
VAcryq_1tTmpwJK8QPZtvb4_ocRCvGamVeHtylVEhBSizYAKxfJNhoUJgofQdyo_QPsCiQf8Sxn-cYVhJxKAn26Vchn-xWXvINmF_tT0IRPi_MRX4QIhz-yF
yjUSV_JvBKYSlx-8z_CNtn_5Utdo0iur06G3mZL0PFz5De1S_ycqm4GBVlINEm00
}


FirebaseEntityColoring(Authentication)
!define Authentication(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Authentication, Authentication)
!define AuthenticationParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Authentication, Authentication)

sprite $PerformanceMonitoring [64x64/16z] {
lLVRjeGW2BLo32UL___RaxUEarWQiuQdDFSM4464k1H4yLIm40Pqd0JRmaFt4E2TyD3N1DWdF7IB04U42KScl2P07W7oy8Wy0kGHD1QuJGFepTqHq61Oyly5
t31-_VJlUa50_31J-3DBfUGSFYVJ9AYdTG3hfBNJWK8ty0qub3FG823n9gjhh1zQamqoVVXzwUJYfZjYYnixFzk5N_DEAY1tsrNMQgK8pkT-s6wbYcnm-C3L
-FFClcp-z4MsUpuvbSOlGMjGDe_y4giW7CjoYtT1otrRUPpRhexqIZZ2W0g_XVKsEis6-7e5LzfWm5OfKCUEtzcy_K2A74bl4uVwxb93EgxYVXnxAiA17NXt
XM_e7-MLp4z2wK_xho3uXtVvpn-IfKspP00IyGDDrooZyLiA7R_j-uC6b9GA35xT7_B-UW_eAIVFIIVhU-vloXzcBjFlREZyWStyTQwl0_ahvizQz5Z-xe3Z
JVqezH-f7sFrwt7zn2_LxsVF1_pY-qNy7l_bzwFuBPxv0ESr0Cm6XDS0CVilPWF8wpyvBJ2Z1RzQyWS0
}


FirebaseEntityColoring(PerformanceMonitoring)
!define PerformanceMonitoring(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, PerformanceMonitoring, PerformanceMonitoring)
!define PerformanceMonitoringParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, PerformanceMonitoring, PerformanceMonitoring)

sprite $ABTesting [64x64/16z] {
pPVR4eCW34HHqNfb__zlwulr1Z5XhUs-ENfs70WawvmemEKA6n6etGHfSRJ605VYQDa0Ed5qoW0MaJX8_6m0pW0S3t06u0m0oW1VuAlz-bQ20R9vtC77tuGG
_0Bx-S7ApweNlXPNy9SyU1v_otzAm6VntLezdM2GUZ5jos-o7wvIKRw2cdtzlup_tn_lry74X-B85y72L-V-uWry6-jlhNh_ntX_7RNdfuZpfPAlK-D1e-Ax
z7pHA_WWp2UdJOpSFxqq7mtNz_T0ylk3Sx43CNwzzu-gGxm1vlPFtDI_7OdpyujxdhzvVdJFykG0pWK0Ce1m0OZCNsG0vF8d4u6922vzyWO0
}


FirebaseEntityColoring(ABTesting)
!define ABTesting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, ABTesting, ABTesting)
!define ABTestingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, ABTesting, ABTesting)

sprite $Invites [64x64/16z] {
lPVR4eCW34HHB59Ai___jnrjwJZJXalMCGy-SHQ4JI3ELGDmri0X27HS17fmT8y0Mi7HTG7q1KTh0XW94WU9_mg04m370vm0E87Mo1nZhWWqQ5csGOjOUVyU
vRK5DF1KfacAG8DV2x_-vrkR5meVJ7oU2tyty7Bx7lACSJxk9pTjtoah7ghi_BRq-G69oorg7bJfvswRsFBm7xE6A9zj3u9H_drSOVjddpjoI7EBcr9N4cf9
kPfoEdzdnpKyk_wpzs_m_A3vHwp-6VLlH_uWXJKP-9A_Um7rOk2FzSDR-6FzUjZgPonyjDNlUwD-kjwKo3Q-N011lK2x18Bz0eQa9BK7WArMdFX-STVp9xyV
tRKy-G3d6W2o0U4Q8BB_8Xj0hlzaMc2Y1QyDUG40
}


FirebaseEntityColoring(Invites)
!define Invites(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Invites, Invites)
!define InvitesParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Invites, Invites)


sprite $Functions [64x64/16z] {
tPVR2iGW34H3KNmHv___Tc_iiZM9LSTsOVCII7C6gMqk8aq3PDRmPGGwBWBVEBf704V6qMq1z1b7Um8OCH87YMi1S0BWU80J02TGFIYnw6mZwE6RR2hN2jhy
FLDKhXc4YukaVJGzWxQ0XSVw_D4KwCOT0SMx-4UWoHSVVmkKGpvu7qnGF2m-UNooUFmddpEKCtWuV7XTmzvPF4m-Ftokt2ayU_wJtb_l_U7dtuyivzd_Tw1-
O77zcgcVRFrUspyc-jTq_yIY_ZqtFc3X_2BNyuldHxcM9mTmRW4W5n1k0IBtBt81vFPFPWKcLl1MoWq0
}


FirebaseEntityColoring(Functions)
!define Functions(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Functions, Functions)
!define FunctionsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Functions, Functions)

sprite $Crashlytics [64x64/16z] {
lPVX5e8W38LHG37G-_vl6wMGfm37vcc_0lokX1lRb6eQeBY6amdGVX7KJKPJ171bChej09h9w9e0Uao8GuZ_2a0c01aFo0GW4wW-ihXeuKgWYjjzFN3vOtrg
hvTMd770Tl2s_OB2l8dJXiXNy2YmCldfu3IJ__RjNduayoZo8O7Z4h1vs-HBitx77SM7KHMOmUAdCThhzD-ZhPUVqvz_nC6ghxRnm-jpL0ol7qjNL2T-oEUe
MVn8uudx3sG-dvy_dvysL3v_FtFwVY4D2Npsdu_xROEg293yD-m1PHZniqQnT1sK14ZncssXyTNwmj7ux_ihxsTbtf_-un6y-zkNSP3pHx0sTEIFhlp5pf-u
AN_poWVSMB-e__Ctru_glxom09Sr0C86HDO02VilOGCewpybBR2W1MyzyWG0
}


FirebaseEntityColoring(Crashlytics)
!define Crashlytics(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, Crashlytics, Crashlytics)
!define CrashlyticsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, Crashlytics, Crashlytics)

sprite $Hosting [64x64/16z] {
lPVhceGW28QDJhgPtF_TxkXCkuQG6Zt3hndj_I9G56Ck3T7SDSnCWVQBe6mwkaK0QwQZhmMmpNIq980zfiHHYPS2g1D07O-e4q2TWF10s9orRWir0HwsSCo3
3RryMC_nNOCim4puWUPtyA90EUpEBAGlSG9VnSto7d6DlAU-RuXxTC4tyO5-kqsZBu4XjF1vv1VlZvVkCGkS0_JrnQkpg30Eq14hyGZaFyz3pZkI5gZo8Siw
JCLKgF7RAynZnCSosv1IIGJAjJFXoFCplmXf-1QC0Wo_C07a-UH1iNKudlMV2CoVkOdndudVEqbZoRV4xpz98-K3km2P93coakQEzHC327_fEl7y-kK-m1tX
_YHWcgouVzZzkySVF_bEc5ltRweV44uE92Uu-e5I_OBamJwV2f7lgP-MrYAfVae2yTHPht6id1y0zywFllFhzlc93vtVzwuF-E3znNoVV_Z-QBxBAo_WkWP0
sO3e6Y1b_wLi07NzfwO5LhJWLu_y0W00
}


FirebaseEntityColoring(Hosting)
!define Hosting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Hosting, Hosting)
!define HostingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Hosting, Hosting)

sprite $Messaging [64x64/16z] {
lPVfjeGW283TpPNtVzkhDQV9ND9Xxl2dK_eXe90GCXG0ygd0HH3ekXBe2uwUKG1FWgF72c1ES7HF0Qm84WSaNYi0d0B0yG0u1O1J081I0F_3Mya8OMAB3mhQ
OuQUxgauLD0SaNc42Sdpa_e1tnp8c0g76yaBujPuMQofqbjSuMq2mkKzAH3Jl5SvShRubbpmFGMtBsgFAQiCKXs-4JWgjQlcKHic-1muszaFmlqJxtgH5iT9
CWyyx-sqtVIkehAju6EoiPyk8Uq27IQK9qGFXaFBWzisRVV0sN9lvSX-Lw-VJDPdH8Ee_BlxprePAi-W1ZlYypbrpHh3UdwNlBabphL8gfdpbxUeM8g_on0H
zZ5_OfvEXThb5KjlzL66qiYz65Rv5_bxlUAmH6TKhaGoZFCN3Alv16l16Zuqwq_qzf2NyQmRmwKB5pSBzRlYfL-g_oNFjhZu_xZE46vit92_fCydFs0x4nlS
x_iBznVoU_xBzqVoMnvv0SSr0CW61DS08VilP0E8wpynBJ2Y1HzD-GC0
}


FirebaseEntityColoring(Messaging)
!define Messaging(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Messaging, Messaging)
!define MessagingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Messaging, Messaging)

sprite $InAppMessaging [64x64/16z] {
lPVB5eCW34IZG4LvvF__jhgmLGmAZ3fBZtS4aaX2T2fcQXLl1A3r9fmNHfSOy9Km-jo0ouJHEGEk4OWpY1yD63DWZ1VVY5kT6mYmIJQeGzxWY0SXm3vd8AnT
2NnVpaSnmp8B43xlY3gxLqyqocSey1EHIXxDvsb5dX_W7SXp67GB7uUOorUHvvGdCgwEFyQz7p5-rYTW_5mk3kEN18pNFAVX2yv-TBTkmr_o6Vd9cgK6rOJn
tIyXAjQlrlN_lrx8x-f-7yHANer5ySlmnYFvQoDGFzeXzGVMxyR88BnxyVz93_3e_L5rVpNVdtpJ_ItkeAP_WFkNXlw9x-o_yFwHtkN11XmR0C0111k0mFaB
702n-HCPWO4H_EoLBm00
}


FirebaseEntityColoring(InAppMessaging)
!define InAppMessaging(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, InAppMessaging, InAppMessaging)
!define InAppMessagingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, InAppMessaging, InAppMessaging)

