sprite $DynamicLinks [64x64/16z] {
fTK7RiGm44DHRcyQyFwtpI1XkaK8vaVP-jmbmKTYR_nHG3kLQ9NfBk0gqrt0LQQxWAkGC-DTwXboPhnBFJFUhV7SroXkjiBh0dINuaRofWUW7XDl-HtTyNn4
zp3Uy5EHh3E0cdZBBtf_qblZ7MTj_jNv4bV7xHFWlDS77tpl30ok-wBa1SyT-xzBDGU6EVyPRqNnYmx_ml_1NdbnlIdIv_bZbJys-PrSE_wot7lz-_oB3_55
hoirnBkd-98lu2ZrzVZLbF_tGuV_w_6RUqptJtFVZQS4pPMtlit9S-yBmBb8rcc1OpBdQj8KDnv-qbxrVj7mtYzQddVS6rJ8aV4kurtgCzvbl4jzm5N6kq2h
Z7UPxWAkCjvbMXcxtW9z0m
}


FirebaseEntityColoring(DynamicLinks)
!define DynamicLinks(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, DynamicLinks, DynamicLinks)
!define DynamicLinksParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, DynamicLinks, DynamicLinks)

sprite $Firestore [64x64/16z] {
lTPNgiOW54NXWq4K4Pt_Q6zlctkoMVmbw_rBjOLlxxYr_QSRgNQJreYs4Uxp6kGuosYMuJ33KOQpZ6SPZZASPJoBy37y1Jpl9QBq6_rgyLLREy_mMUDFTUwq
Cp-E2EqOPpvzxQJIcM-2v5ADU7reVHNezQFDAbuwzstfhynzVidaM_L2lVohtkMV4b_dxsFhYypglJQhViYyCpyEF_fylTZHvrijqjf2pr_bmUKrAl4wRNKY
Gw_FkzeDldJzddpyvlzh77p-r9cF9-RR-WU_NcOrv_r0rAjoN-mQp0vSVlqCvFMFS4_s3nVOlyBwqk46d0VsR_My1vvVudeVsWrSkzP7qWrSkqLhZ9k0zX7k
ynnaDCzO7g2l
}


FirebaseEntityColoring(Firestore)
!define Firestore(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Firestore, Firestore)
!define FirestoreParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Firestore, Firestore)

sprite $Predictions [64x64/16z] {
fTO5TeHG44JHmlb6xN-twIXsYlHClt6vkE4v4k_6Gm6wvzQwcBQ2t8ffAyYjcBQ2t0fo1ZaPzGno1ZaPzTIy_hxijR-NFSLPXcfwADoRvurCFLsU8wO98mzj
mD8ZyPJYRB0QZoq0UbvIdltjpnN0SlE2PrYPnqPOczDtVSvznqC5Orqm-tnQQQs9UtCXkSrDU5qP4tN_-WnWeSp1KuVLuHMlRFi0jDUSDW0aXrUSJ1WfmYD7
ebM1GftcLlhY-LqEf6SEoVSoTOXnmiaJQPLwypxEjSjiut3Zy76oHm_KkuUFCmEOABpcJg-vU_erryiFbeFBzOVh06vSf7mdkDVN5xaOW8yJOW1-VlUitQiy
Vls2g0zo8CY1g0zoAyW1jvO5EH3JLf1RGGu4z5x0xZde1m
}


FirebaseEntityColoring(Predictions)
!define Predictions(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Predictions, Predictions)
!define PredictionsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Predictions, Predictions)

sprite $MLKit [64x64/16z] {
fTG7ZiD034DHfan9R4ltF-qMOgFKqMBCZvBwJ5GXpnrxyuS4Ua_JJD5CuapHJE9CqKpYJEIkSAPw5xahdAdU5SuqhdjF-NOr_sjPiWSCE71mPmteO--VAm1M
lZC0frc_8dpRuqjummw_8NnBl8zy2M_8V3fFt_Ru4jumwpaVlatwc3_I6tBl6CmVEdq3K0-97yrVw3blavxpJizvppm6y_GBvsTypDEVEJ_fEK_FRCR7VFZg
gGS-pVUxj_yyFis7hpxZOpwypVYO3rzzniTyUBlvUoMzFvmFNvqTyTYQtUz3dEebvhtWCSlyMkFIN-fjoLgzjthY9mEOwY5oA9mfdAbUuKpXJFKIPmfdacOA
Pufc4cSAPugE51lbb7q3
}


FirebaseEntityColoring(MLKit)
!define MLKit(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, MLKit, MLKit)
!define MLKitParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, MLKit, MLKit)

sprite $AppIndexing [64x64/16z] {
fT9NSiOW40JX1cMfqDp_jgvr-YCghwUV-SXS9_7VT9T1yvEedwKZZqUMZZmUMJhoU6HoMJnolKmkYqUkbyMZFlVzCTT2dNPTrUL7vRkowQAENxbhKhyBFksj
7Gl0cFG7K9iKdHEmvdo5gjycuCpu0sYwLM1HhpT-Vhgo3QfwlT_-hhjE8ECBjESzjeH_6LvoliBnFE6fNgz-Uhhl7OeIxK_h3J0hKu7fyJCt9VQl3PZk-QoK
rmIKxPIq3q1Hqck4g01H6PDUAx_DAZ1qENhRkLI0ChVOJNy2GBrQEtzVa27le_u4D-zC4DwOWF361AGcc1slOPRbrU7WUaoEoS7au7gJWyd1zHwFJ0wUZamE
beuy7faS37tBiBV-G3y
}


FirebaseEntityColoring(AppIndexing)
!define AppIndexing(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, AppIndexing, AppIndexing)
!define AppIndexingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, AppIndexing, AppIndexing)

sprite $RealtimeDatabase [64x64/16z] {
pTK5RWGn44JHzZAwxd_Rg0J1yggL7zWl77Z3OzVZfFfkqbk0liMq7DAESOUqOzmXxHXta0jnHxqW5-AEUY7k8kV-D2esJlfKvhNiom6I7si_aW_hRZDqgwgc
dmhD9_JA_d8BNR9NyBa_z9k1_4tQzBoYdzAMp0zNQVGz-FxJzH_N_jZnEgpuGGtlPang-Sk3Vk7xgr_mOxT1_YvjsfvylujrvtaVBPzMRchP9da-Vy3vgqGd
KCWBSOUuenvnXxYZdd67k6FQ8UwGTemxn1tGRm7xLeE-
}


FirebaseEntityColoring(RealtimeDatabase)
!define RealtimeDatabase(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, RealtimeDatabase, RealtimeDatabase)
!define RealtimeDatabaseParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, RealtimeDatabase, RealtimeDatabase)

sprite $CrashReporting [64x64/16z] {
pTLbcWCX48JXfeSOLlS_xGeL3vCdRArz_zyHr9u7s5V3LGAz96acQAPm9cYcS2Pefd0cSWYSgHuYXy2PwY5mzeJhliQ6OorM37l6WtaxShTGCMpTxytCsv6R
xTSziFw0w1x9fpssTcw7UL_2nOSoxQlTL35kv5lvo6-zbu_Qo0z7Rjp-T_p1FH1upth1_V22PuK4FJwiODZOfqUVC4xrslZ1_fz7QmV-V-ln_m-j_S3uszZd
HvzVtZyfniLwiMUz9SOqzCBu_OolwIE_fPu-gXFdJxdrPVRyHYPa6TCUTR5ZIyMaPsMxXB1i2rOvWtg1Yjm4pWJEL2zm9d2cUeKpWJD5Cu4pGJE5Cu4pJHyJ
xAKNw3i
}


FirebaseEntityColoring(CrashReporting)
!define CrashReporting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, CrashReporting, CrashReporting)
!define CrashReportingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, CrashReporting, CrashReporting)

sprite $Storage [64x64/16z] {
tTK5beDG50JH5znx_wiTwpXsFZLUyS359RQJucYw2z1RI3kW7U4EQ4Uu0zeHxY0Nu8vwGIx07VK2t37ElHRvq3QNjDVSgufRkNQQypxkovDz4m_btNtJlgzZ
gmRw6FHOgczcNac-_cTUrElhVT4UM_xiUWxKHtmsVNm_JPBA0twK2dz8ofDz9qbPzFfeoXBtlqSSEycDfnKVYxxGSqEAF_N3h2h1hyLzqlLpNfzo_PvNwR6j
-yUyTj2MJoySzG5v0Eu0TzG3xW1tr1Fk07T4Ey0Tq8vm1xW3-XQmjxHFNm4
}


FirebaseEntityColoring(Storage)
!define Storage(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Storage, Storage)
!define StorageParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Storage, Storage)

sprite $Analytics [64x64/16z] {
vTK5TiD040JH5RFw_gSDrOj9jDeEfnwOvfkb2Vj98JNTPD1hbYP3ayF9qEHmCZGvd4mkWvFhPN8Pd5olKtpgsb4FdU1jUAbAzWE3hUwBvQgPpFLGh2y2hNdz
Oo_Vwm_xwSKLqvxNdfz1yuwF-TVNgJu7vQdlFmDbVzW7suTFyDFi-Fx5vMEo7q1pZ5_UTvbjOdrOtofbgiylHqrvUQOp-wDbTf1whlKx-slj2QhBQCCNSTcV
aGjuRBlf_LexxkzlV4fmCZYvtk1aS7AzmydWv6WoE1cQ74u69qTVSkob2FeC
}


FirebaseEntityColoring(Analytics)
!define Analytics(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Analytics, Analytics)
!define AnalyticsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Analytics, Analytics)

sprite $RemoteConfig [64x64/16z] {
fTLLSiH060DX9LaqwVwd3QbInadzw-vdVwOX_P-jitaHe7D89w0JuGdeH7W2EX6U83VWYNf3Ri0JzGOybJdtGz--WIjUZHkKlVg6Tz6hVysFtQAxSeEwlsfV
N_SF7NJrjgQ_IE-NkGzzT_6k5lStw3mtX1D_CV8N8n--h-Wdrvjz8URv-zF_1yVFSFxm-IjlkloMrVfihf-sbzARxVk9zVl7-xtlAxxxBPSEXVsBxPzy_-Rd
1po_P7g0GYx04-29Ui0Ju8bwmXFWYUW4U08w4Pu0Jq3F0JjNe5y
}


FirebaseEntityColoring(RemoteConfig)
!define RemoteConfig(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, RemoteConfig, RemoteConfig)
!define RemoteConfigParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, RemoteConfig, RemoteConfig)

sprite $AppDistribution [64x64/16z] {
pTI5hkim08DXbxCK_FvlU-LHHW5T7_f5ew_WIKKv4lyRcJ9eojDKbbOULvPM7bUMLXvN9gV5bUjfSbfSkPuMLnxtFIskN9_deSyqx2r-HRQvnGTaMrhyXajn
Uwu78fdAUSOHwiDWs_DxvZewe2TFuTx60m9jdYCmaKX5pThN_N4kGbiTIEsQTQpvhNi-OugSd-PNxxv_FUEjdXnqo4hTwnaltSROMMbvFUEjmFtz7mNVYY64
kGSQvfVFD7wUVshrwuVv9s1fzH70LfqVENze078Dz-Ad-Ly6FOsBBdqS1-1jgpH_paTee1tNXksv0FH5FmFeU4A-gUWbH-x85yhFpwMV3Z8EVQRnS9_VVyhZ
akjXSbXSMLovtkBAuihr7bSMLvvM5bUMLXvN5bU6JXasrK3_0G
}


FirebaseEntityColoring(AppDistribution)
!define AppDistribution(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, AppDistribution, AppDistribution)
!define AppDistributionParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, AppDistribution, AppDistribution)

sprite $TestLab [64x64/16z] {
lTO5TiD054DHcTb__wijg62QKHBhj2yCrqpGHU1kiSkWMvvcZcOMPuvc5cUEPXPd9W-7CzU7oGEQh_iYbV1BZMDDQX1PFkFQ8WOGfyg4hvxtCrBbvo1E3K3P
7ok0AH8bVGyqSQm2nfoF__6S_lMsRpzVkcA-wHjoe5ZYq9D-84zi1XkNFiErrrnxnP_ti-HC-HwTv2plH-1x06s6QxzM783coFXj088BlmsWKbnx3a1oxJa0
pRNd0CZxCUEXVQmjlyDTptfulleZ3_WUflVF7yRvopf_Xdl-thnr_U1Vlo1ahjUSEPovtkBCuSpIpE7CqSpYpE7Cq5k6tNg2lWC
}


FirebaseEntityColoring(TestLab)
!define TestLab(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, TestLab, TestLab)
!define TestLabParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, TestLab, TestLab)

sprite $Authentication [64x64/16z] {
pTG7SeCm58JXDseqINl_soOxvasQR0ERzazJ-rm1UnnWLmFU4kXRWlOapJJE9CqqpYJDDCv43eaprKFaa3XJFIJEDAvxI9pfVinHSqWpzkOKSZtbPsEXSTo2
iVc4htOhSHBjLZtki-qreFcuOD3O1pShiFWuZZq69JSRiFau7VUpcmvq7y_7FOAJjnSBEE5RTEul41k66SRLTUi-xjlQy4ypZEfrNTQt3_qwgVsmtqgmlJHt
q7CSodR4hplsSWFy8WphKv_jIqJ1N-t9_rziK0Dc7vV7zu-Dce3Dl8U-3tq6gddzFtdxxCEe0jJWTVNv_O-ytLAzYTmapYJEL2zn9d6cUeqpYJDDCuapIJED
CuapINk2VUi0VG4
}


FirebaseEntityColoring(Authentication)
!define Authentication(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Authentication, Authentication)
!define AuthenticationParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Authentication, Authentication)

sprite $PerformanceMonitoring [64x64/16z] {
fPPNOiGW34JbBjQ0xd_Rn6FOAWUoyxws-9b1LFaRC_aMUu9G7t0sO6n0wO2n0QK3nWQK3aZT61smlf6wCJfWVMlgUG-gOS-j5_YoJbAODF_RtmHKDlEurEE0
VyPvNUTH3ePe3XT-W1ooWHpmYk3vrxhQ4ueNTFgnnetf-9fYxL3iyuTV_OYkCFQpuNpyskLljQKLvYYo8fKx2fz-llSzpUlvDhtN87_uptfzR7okHKs39Dhs
9wJMDPLlI9XMnR1CJJyZPHIPInZ4cOyG-AlbxtW-dKLBSh2Wb0aTs3y2VCmTj1nlPcYsbEyMpw_16YXQBa2lRIA5Vk5dns_aBoob-y3FxzUliZpfVVNBWb9x
96y2UlD7BqipTSvV3ypVtlK3egxpl6gqw_NZhrzK80nI609wtxL-w_uHHtbYZFx-OPVxbxpHkN-182wXV__krArnVbGQvmTnVb7df_7dT_N92mYZ0zPdTC3e
WFKf7J0we6p0w82n0QK3HWUKNI7S1ntg3m
}


FirebaseEntityColoring(PerformanceMonitoring)
!define PerformanceMonitoring(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, PerformanceMonitoring, PerformanceMonitoring)
!define PerformanceMonitoringParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, PerformanceMonitoring, PerformanceMonitoring)

sprite $ABTesting [64x64/16z] {
pTL5WiCm0CLG1SlM_Myxgt8T-aFQlu2HwPIj-L10xmNwMgRLaAkPLaEkPbeDkHfoGwwfD-I6N5DloBNESz_nLEUdAdonD_LLRYcbl-A-bBBMgyFL3-h_zERU
V-kxg-yt-GDSErYjwYyyT75rBGzrhctagTtAxp_oqccLBmqlDMMDxtYhN-7tV6Y_UFxFVEoyTFyqVAnTw0SgZOlyWMh71RvGhodpvyyHwftcp-zJw6sfrhh0
bvvAG_d4mVG23JaXXv13waCE8OVKXnm8EMGQ8EIGQI3aGCWXqjS2Usy1_G8
}


FirebaseEntityColoring(ABTesting)
!define ABTesting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, ABTesting, ABTesting)
!define ABTestingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, ABTesting, ABTesting)

sprite $Invites [64x64/16z] {
fTLNOiCW40PXr6WcxFrFwpxf8UkVSNdxr5c5SMP1pJubKQ89JR8cdPEiIUSaQz8vgPnaJh8dbPFCIVRavotdPZzpyhw7QtjN_HRkRVOZ5w_XMRKVUNp2fz-z
_LF4Hyct5Ly4tuz0gxtky_tEBRV_fTal3NrTRxizMS_xaUtN1lpj_jZWpErRZha_BtlizfhdTiNREM_DoErJeAMQ8pm5IgRKu8i92Nxs-6Uldth_wA_dfm-U
7_7vbTUFrPYgu5c_s-r_wmFlcH_RmBlcrqcRdncVjVbTy4Np3TyqRt4m_lqRYFeBs7gjVS3n_k0aSvhrCYUPqwpNEScST4qo9rcJpadcDAL9iaGEUW4
}


FirebaseEntityColoring(Invites)
!define Invites(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Invites, Invites)
!define InvitesParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Invites, Invites)


sprite $Extensions [64x64/16z] {
fTDLTiL030HHcTdQ_sf37OxEb5vK_xUDO-tSxR_vjnwbOIMj2benfq1pn3dG776ko1quL_LUv0wSgthFy6rOO23WzxAvMiriVjHVdTcYgvlHGCmr88u3Vxa6
LbCQ2_lBxyw2xhHV8pvvsky17ptlVKvo9HyC85VYhO71mSFHsjtLEcmvlvbIYwl5pDQCF-ndsmUF1u1hG3mQ02vqYUjrD3iD6jltFv9Vstu6FdlR-m2Sl0-F
SNaU40zyVc3odBy7uE3zxe63rq2Ao_F0wB67WOYprm1my1f0tXeOJIqEtZpkd8T-N2xavX1mim9NLL_Wgi1LrLUuAd1LqQh0LK4hv1Xm3dGkiBaIz1a
}


FirebaseEntityColoring(Extensions)
!define Extensions(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Extensions, Extensions)
!define ExtensionsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Extensions, Extensions)

sprite $Functions [64x64/16z] {
tTQ5WSCm00J12tEs_sgVIHJQvml3s1OhfmEvDNo8eEzn6W2d0Sa1fm790QS1oG79aHoiHt8a1-iPykFY29p_SiIdcHuPVjdwvfzf_jlzaY5FLXHP9SC3zFW2
oYow1pZ9nmSO-uOt1pZfZmrl3d0yw-SCCcyyFRyQ-LNFyp_zVa_pql4C_3oPDoyzJzVlasHVlbZ_DTV_DVNNvejyj8_oTlpA-GCvV_dvqy_VVlqGwvTQFx7h
T-7D1aJon7h94ycJx_NfHF94w9T8dZYTHF8aaYT6Zm-I6y9vUWy
}


FirebaseEntityColoring(Functions)
!define Functions(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Functions, Functions)
!define FunctionsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Functions, Functions)

sprite $Crashlytics [64x64/16z] {
fTPLWWCn38DX3tDq_zkkIYwwpLh_-pSOiky1bWqF2HHUNdkQPY9dccOYPvfc8cSYXyQPwY5oQ9of7XLycTcEe9zyi7Dxrjkb4K4nd_iPA5S_82holPdr5Jxc
h3-IVhowBkdDo_csskEZts-mNNQKRVZgyQ7jmcV4nTulC27bnvQHTm0h__MJNLi17DslntZp59V06cCBQdlqZN_7BkNR1wy__rxj_VjjZz-lwskz_x-BABSH
sLTuRtiUVgNnwsN6xtwPK7rY_Xp0DjgrljAt5hJKUOkQ8_zz_VBdEPBhv-OZ8hb-RvyvglUFVHXsH5xOlwJz4-h-xJwLUdvvJFKQPnfdgXSvqpXBQq_ZJDDC
v4pZJD6UOhqA-WS
}


FirebaseEntityColoring(Crashlytics)
!define Crashlytics(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_AMBER, Crashlytics, Crashlytics)
!define CrashlyticsParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_AMBER, Crashlytics, Crashlytics)

sprite $Hosting [64x64/16z] {
lTPNakCm38JX5fH01VRzJxixUUGkg2YCm_zgVyeCa2GIVus7iZGifUFIMijpBQsrFDVIMijpxKxEDDVkzRoJKtY-UpsRlAx5lQorTO0Ok-4hyvhrTSPDSsNG
ATywIDt6e1DVS9CP09JOjpacblW0iTyWhUHk0BPBldR2dIIh0LszukVZbM_Rnizs03CrzMJ58PUd4bm09J_pDC3Rtd2eo6knqCUNRsO3zQVQyYlGzG3Gave1
AoNr1HZOntu42XivC95zw2V0htdsCdJ4DwvV3Z3oio6u_k3v6UK0O-FvnI-f5n--FqRVJv4lQKnyF_IVVutY3V1huwTyFUwlkc7mi_4JZz-T91SS6kFnUp9_
MFsyW4DTD7_mRFwodIJt4SUspFpfEXUXvEPlyyfPkDPOFymowqT-_Rfp_UIzwxVuP0_Sl-3r_jxze_PQZw0qr_9QItCjhRKyrz9SI-gumEQxGFy3
}


FirebaseEntityColoring(Hosting)
!define Hosting(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_YELLOW, Hosting, Hosting)
!define HostingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_YELLOW, Hosting, Hosting)

sprite $Messaging [64x64/16z] {
fTPdaeOW48JX9d-IvlwttIcB3HQBgT-_-fW5S9u8tYP_8kXlZ1vnMYEvnccDv1gdDP9h91UEQwmNaWl7DTOBnxLJpliSB63zfykgCxuPO1IxB5hx0CtwuA2P
kl1BhWonYMZP0YZFV3YSCmAcF_5PGPFV8k1l-neDW2n_iq2L_vfz13GxNL1S-Fd1mOHKflrCRgV-zy7bnVk0grU-h9wqnzvsuTtgJUTFyj2cQplu3ZXPrYnW
vAmA95dNvZkONjD7ZhbyVBVXxFhBV7x0f2wZvk4kxjzENWj5HYsVUR50cRrcDvcR_GQODlkzUEVxiu0vdCeP_EJpvV_J3G3ZurwIlPfJSDWpdtxkfJlyP0uR
oXOjWD3ElBRPsIjEtevxEFTQhrdJniNRvJDyjE1os_zRx_bGHLvxEvxxE-_B-SMTUfCwCm5dMKVE__YDunhhEQvnN6CzoJMEQuGUSLpZj4PoZUCQfqU4_Uq6
_G8
}


FirebaseEntityColoring(Messaging)
!define Messaging(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, Messaging, Messaging)
!define MessagingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, Messaging, Messaging)

sprite $InAppMessaging [64x64/16z] {
lTP5beLG54FHu7up_zbMEhYJLV_qD_eCrv7u6XSPTCxGOvvM9bUULYPNdbOcLoQdnvNhQNBUyrZ6NTS-2gpB1swwuWFszTnqpfbXN_hS1_3y0RYl0v9wNGeq
t7RcMo3ZkWAe3pt_mNUcvr3bNtnKmR4ddbiF5Dqxl__lQUDvLGwMLtbdUPNKSUy9hXkwkioJyJNwdNzOtzP51Y1hFPzKyVxvimHglFiR7nWRV-9NdpLKNttH
E-Et3cF-v9qn_wpvkxvGuVZkX-idJE_l7yR-PUsVjFVlqNld1__y0hxCzrZdSULwaokFAqz3ULnvMfbSULnPUiomSm_e7m
}


FirebaseEntityColoring(InAppMessaging)
!define InAppMessaging(alias, label, part_desc) FirebaseEntity(alias, label, part_desc, FIREBASE_CORAL, InAppMessaging, InAppMessaging)
!define InAppMessagingParticipant(alias, label, part_desc) FirebaseParticipant(alias, label, part_desc, FIREBASE_CORAL, InAppMessaging, InAppMessaging)

